### ISSUE TITLE
Can I make this model only fully supervised?

### ISSUE THREAD

**Issue by nanaBaah** [leggedrobotics/DeLORA#6]
Is it possible to switch the network to be fully supervised instead of self-supervised?

If so, how can this be done?

Thanks in advance.

**Comment by nubertj** [comment]
Hi @nanaBaah ,
Yes sure, this would be relatively easy, and of course less coding involved compare to the self-supervised way.

Instead of calling this function at all: https://github.com/leggedrobotics/DeLORA/blob/909948d63a9517e6dd54bedcf099f6b39ded2cb4/src/deploy/deployer.py#L302
You would simply take the loss of the network output https://github.com/leggedrobotics/DeLORA/blob/909948d63a9517e6dd54bedcf099f6b39ded2cb4/src/deploy/deployer.py#L276
by comparing it to the supervision reference.

Best,
Julian

**Comment by Rhett98** [comment]
> Is it possible to switch the network to be fully supervised instead of self-supervised?
> 
> If so, how can this be done?
> 
> Thanks in advance.

Do you try supervised method? I just use self.lossTransformation as loss function and I got a bad result.
