### ISSUE TITLE
Calculation of the parameters

### ISSUE THREAD

**Issue by nanaBaah** [leggedrobotics/DeLORA#9]
In the config_datasets.yaml file, how were these values calculated?

1. horizontal_cells_preprocessing
2.  horizontal_cells 

thanks in advance :)

**Comment by nubertj** [comment]
Hi @nanaBaah ,
Sorry for the late reply. The horizontal_cells_preprocessing were calculated using the sensor configuration. E.g. I think that our lidar provides roughly 2048 rays per rotation, and to make sure we catch all this value was set to 10% larger than that.
The horizontal_cells was set to 720 because we chose this to be the input of our network. By choosing this number smaller than the resolution of the sensor you get a more dense image and reduce computational complexity.

Hope this helps!
Best,
Julian
